
name: CSP451 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run a basic command
      - name: Run a command
        run: echo "Hello, GitHub Actions!"
